from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template


urlpatterns =patterns('gps.apps.DataProc.views',
    (r'bulkProcess/(?P<year_1>\w{4})/(?P<day_1>\w{3})/(?P<year_2>\w{4})/(?P<day_2>\w{3})/(?P<IGS>\w{4})$','bulkProcess'),
    (r'baseline$','baseline'),
    (r'baselineProcess$','baselineProcess'),
    (r'atmosphereProcess$','atmosphereProcess'),
    #(r'ionosphere$','ionosphere'),
    #(r'ionosphereProcess$','ionosphereProcess'),
    (r'highFrequencyData$','highFrequencyData'),
    (r'atmosphericDelay$','atmosphericDelay'),
    (r'datatrackrt$','datatrackrt'),
    (r'datatrack$','datatrack'),
    (r'trackProcess$','trackProcess'),
    (r'trackRTProcess$','trackRTProcess'),
    (r'trackRT_View$','trackRTView'),
    (r'killTrackRT$','killTrackRT'),
    (r'modifyConfigFile$','modifyConfigFile'),
    (r'writeConfigFile$','writeConfigFile'),
    (r'tableStatistic$','tableStatistic'),
    #(r'initProcess$','initProcess'),
    (r'dataStatisticDetail$','dataStatisticDetail'),
    (r'tableStatisticDetail/(?P<filename>\w+\.?\w*)$','tableStatisticDetail'),
    (r'configEditDetail/(?P<filename>\w+\.?\w*)$','configEditDetail'),
    (r'configEdit$','configEdit'),
    (r'saveConfigFile/(?P<filename>\w+\.?\w*)$','saveConfigFile'),
    (r'resetConfigFile$','resetConfigFile'),
    (r'readGamitLog/(?P<year>\w{4})$','readGamitLog'),
)
